name: Deploy from current branch

on:
  push:
    branches:
      - current
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.husky/**'
      - '.vscode/**'
      - 'docs/**'
      - 'jest/**'
      - 'mocks/**'
      - 'playwright/**'
      - 'stubs/**'
      - 'tools/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish_image:
    name: Publish Docker image
    uses: './.github/workflows/publish-image.yml'
    secrets: inherit
